name: whisper_ggml_new
description: OpenAI Whisper ASR (Automatic Speech Recognition) for Flutter
version: 1.7.0
repository: https://github.com/jagadeeshchoudhary/whisper_ggml_new

environment:
  sdk: ^3.9.2
  flutter: ">=3.28.0"

dependencies:
  flutter:
    sdk: flutter

  ffi: ^2.1.4
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  plugin_platform_interface: ^2.1.8
  universal_io: ^2.2.2
  ffmpeg_kit_flutter_new_full: ^2.0.0
  path_provider: ^2.1.5
  flutter_riverpod: ^3.0.3

dev_dependencies:
  build_runner: ^2.4.15
  ffigen: ^20.1.1
  flutter_lints: ^6.0.0
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  very_good_analysis: ^10.0.0

topics:
  - 'ggml'
  - 'artificial-intelligence'
  - 'machine-learning'

flutter:
  uses-material-design: true
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true